name: build

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build.yml"
      - "include/**"
      - "lib/**"
      - "src/**"
      - "xmake.lua"
      - "xmake-rules.lua"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  xmake:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mode:
          - debug
          - release
        toolchain:
          - msvc
          - clang-cl
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: setup
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "latest"

      - name: config
        run: xmake config -y --mode=${{ matrix.mode }} --toolchain=${{ matrix.toolchain }}

      - name: build
        run: xmake build -y -vD
